import { Event } from './events.types';

export const events: Event[] = [
  {
    id: '1',
    title: 'Kyiv Tech Meetup',
    date: '2026-04-10T18:00:00.000Z',
    location: 'Kyiv',
    shortDescription: 'Evening meetup for engineers and tech leads',
    description: 'Regular local meetup with short talks and open discussion',
  },
  {
    id: '2',
    title: 'Berlin Product Conference',
    date: '2026-05-05T09:00:00.000Z',
    location: 'Berlin',
    shortDescription: 'Conference about product work and metrics',
    description: 'One-day event for product teams',
  },
  {
    id: '3',
    title: 'Remote Engineering Day',
    date: '2026-06-01T12:00:00.000Z',
    location: 'Online',
    shortDescription: 'Online event about remote engineering',
    description: 'Several short talks about distributed teams and daily practical issues',
  },
  {
    id: '4',
    title: 'Design Systems Workshop',
    date: '2026-04-22T10:00:00.000Z',
    location: 'Warsaw',
    shortDescription: 'Practical workshop on design systems',
    description: 'Small group format, we go through real product screens and clean them up',
  },
  {
    id: '5',
    title: 'Pragmatic Microservices',
    date: '2026-05-18T17:30:00.000Z',
    location: 'Berlin',
    shortDescription: 'Talks about microservices from real projects',
    description: 'Engineers share what worked, what broke and what they would not repeat',
  },
  {
    id: '6',
    title: 'Frontend Performance Clinic',
    date: '2026-04-30T08:30:00.000Z',
    location: 'Prague',
    shortDescription: 'Session focused on frontend performance',
    description: 'We look at real apps, measure them and try simple fixes on the spot',
  },
  {
    id: '7',
    title: 'Data Engineering Meetup',
    date: '2026-06-12T19:00:00.000Z',
    location: 'Vilnius',
    shortDescription: 'Meetup about data pipelines',
    description: 'Lightweight evening meetup with two talks and a Q&A part',
  },
  {
    id: '8',
    title: 'Product Discovery Evening',
    date: '2026-05-02T16:00:00.000Z',
    location: 'Online',
    shortDescription: 'Online event about product discovery',
    description: 'Short practical sessions around interviews and hypothesis testing',
  },
  {
    id: '9',
    title: 'DevOps Roundtable',
    date: '2026-06-20T11:00:00.000Z',
    location: 'Tallinn',
    shortDescription: 'Roundtable for DevOps and platform engineers',
    description: 'Open discussion format, mostly about incidents and tooling choices',
  },
  {
    id: '10',
    title: 'AI in Production',
    date: '2026-07-03T14:00:00.000Z',
    location: 'London',
    shortDescription: 'Conference on AI in production',
    description: 'Talks from teams that already ship AI features to users',
  },
];

